/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -t noodle.glb 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    bluenoodle: THREE.Mesh
  }
  materials: {
    noodleblue: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Noodle(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/noodle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bluenoodle.geometry} material={materials.noodleblue} />
    </group>
  )
}

useGLTF.preload('/noodle.glb')
